/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as KhutbahRouteImport } from './routes/khutbah'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AzkarRouteImport } from './routes/azkar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as KhutbahIndexRouteImport } from './routes/khutbah.index'
import { Route as AzkarIndexRouteImport } from './routes/azkar.index'
import { Route as QuranIdRouteImport } from './routes/quran.$id'
import { Route as KhutbahIdRouteImport } from './routes/khutbah.$id'
import { Route as AzkarIdRouteImport } from './routes/azkar.$id'
import { Route as AdminKhutabRouteImport } from './routes/admin.khutab'
import { Route as AdminHadithRouteImport } from './routes/admin.hadith'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAzkarRouteImport } from './routes/admin.azkar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const KhutbahRoute = KhutbahRouteImport.update({
  id: '/khutbah',
  path: '/khutbah',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarRoute = AzkarRouteImport.update({
  id: '/azkar',
  path: '/azkar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuranRoute,
} as any)
const KhutbahIndexRoute = KhutbahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KhutbahRoute,
} as any)
const AzkarIndexRoute = AzkarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AzkarRoute,
} as any)
const QuranIdRoute = QuranIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuranRoute,
} as any)
const KhutbahIdRoute = KhutbahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KhutbahRoute,
} as any)
const AzkarIdRoute = AzkarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AzkarRoute,
} as any)
const AdminKhutabRoute = AdminKhutabRouteImport.update({
  id: '/khutab',
  path: '/khutab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHadithRoute = AdminHadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAzkarRoute = AdminAzkarRouteImport.update({
  id: '/azkar',
  path: '/azkar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/azkar': typeof AzkarRouteWithChildren
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRoute
  '/khutbah': typeof KhutbahRouteWithChildren
  '/quran': typeof QuranRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/azkar': typeof AdminAzkarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hadith': typeof AdminHadithRoute
  '/admin/khutab': typeof AdminKhutabRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/khutbah/$id': typeof KhutbahIdRoute
  '/quran/$id': typeof QuranIdRoute
  '/azkar/': typeof AzkarIndexRoute
  '/khutbah/': typeof KhutbahIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/azkar': typeof AdminAzkarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hadith': typeof AdminHadithRoute
  '/admin/khutab': typeof AdminKhutabRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/khutbah/$id': typeof KhutbahIdRoute
  '/quran/$id': typeof QuranIdRoute
  '/azkar': typeof AzkarIndexRoute
  '/khutbah': typeof KhutbahIndexRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/azkar': typeof AzkarRouteWithChildren
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/hadith': typeof HadithRoute
  '/khutbah': typeof KhutbahRouteWithChildren
  '/quran': typeof QuranRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/azkar': typeof AdminAzkarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hadith': typeof AdminHadithRoute
  '/admin/khutab': typeof AdminKhutabRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/khutbah/$id': typeof KhutbahIdRoute
  '/quran/$id': typeof QuranIdRoute
  '/azkar/': typeof AzkarIndexRoute
  '/khutbah/': typeof KhutbahIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/azkar'
    | '/contact'
    | '/favorites'
    | '/hadith'
    | '/khutbah'
    | '/quran'
    | '/sitemap.xml'
    | '/admin/azkar'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/hadith'
    | '/admin/khutab'
    | '/azkar/$id'
    | '/khutbah/$id'
    | '/quran/$id'
    | '/azkar/'
    | '/khutbah/'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/favorites'
    | '/hadith'
    | '/sitemap.xml'
    | '/admin/azkar'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/hadith'
    | '/admin/khutab'
    | '/azkar/$id'
    | '/khutbah/$id'
    | '/quran/$id'
    | '/azkar'
    | '/khutbah'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/azkar'
    | '/contact'
    | '/favorites'
    | '/hadith'
    | '/khutbah'
    | '/quran'
    | '/sitemap.xml'
    | '/admin/azkar'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/hadith'
    | '/admin/khutab'
    | '/azkar/$id'
    | '/khutbah/$id'
    | '/quran/$id'
    | '/azkar/'
    | '/khutbah/'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AzkarRoute: typeof AzkarRouteWithChildren
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  HadithRoute: typeof HadithRoute
  KhutbahRoute: typeof KhutbahRouteWithChildren
  QuranRoute: typeof QuranRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khutbah': {
      id: '/khutbah'
      path: '/khutbah'
      fullPath: '/khutbah'
      preLoaderRoute: typeof KhutbahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar': {
      id: '/azkar'
      path: '/azkar'
      fullPath: '/azkar'
      preLoaderRoute: typeof AzkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof QuranRoute
    }
    '/khutbah/': {
      id: '/khutbah/'
      path: '/'
      fullPath: '/khutbah/'
      preLoaderRoute: typeof KhutbahIndexRouteImport
      parentRoute: typeof KhutbahRoute
    }
    '/azkar/': {
      id: '/azkar/'
      path: '/'
      fullPath: '/azkar/'
      preLoaderRoute: typeof AzkarIndexRouteImport
      parentRoute: typeof AzkarRoute
    }
    '/quran/$id': {
      id: '/quran/$id'
      path: '/$id'
      fullPath: '/quran/$id'
      preLoaderRoute: typeof QuranIdRouteImport
      parentRoute: typeof QuranRoute
    }
    '/khutbah/$id': {
      id: '/khutbah/$id'
      path: '/$id'
      fullPath: '/khutbah/$id'
      preLoaderRoute: typeof KhutbahIdRouteImport
      parentRoute: typeof KhutbahRoute
    }
    '/azkar/$id': {
      id: '/azkar/$id'
      path: '/$id'
      fullPath: '/azkar/$id'
      preLoaderRoute: typeof AzkarIdRouteImport
      parentRoute: typeof AzkarRoute
    }
    '/admin/khutab': {
      id: '/admin/khutab'
      path: '/khutab'
      fullPath: '/admin/khutab'
      preLoaderRoute: typeof AdminKhutabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hadith': {
      id: '/admin/hadith'
      path: '/hadith'
      fullPath: '/admin/hadith'
      preLoaderRoute: typeof AdminHadithRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azkar': {
      id: '/admin/azkar'
      path: '/azkar'
      fullPath: '/admin/azkar'
      preLoaderRoute: typeof AdminAzkarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAzkarRoute: typeof AdminAzkarRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHadithRoute: typeof AdminHadithRoute
  AdminKhutabRoute: typeof AdminKhutabRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAzkarRoute: AdminAzkarRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHadithRoute: AdminHadithRoute,
  AdminKhutabRoute: AdminKhutabRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AzkarRouteChildren {
  AzkarIdRoute: typeof AzkarIdRoute
  AzkarIndexRoute: typeof AzkarIndexRoute
}

const AzkarRouteChildren: AzkarRouteChildren = {
  AzkarIdRoute: AzkarIdRoute,
  AzkarIndexRoute: AzkarIndexRoute,
}

const AzkarRouteWithChildren = AzkarRoute._addFileChildren(AzkarRouteChildren)

interface KhutbahRouteChildren {
  KhutbahIdRoute: typeof KhutbahIdRoute
  KhutbahIndexRoute: typeof KhutbahIndexRoute
}

const KhutbahRouteChildren: KhutbahRouteChildren = {
  KhutbahIdRoute: KhutbahIdRoute,
  KhutbahIndexRoute: KhutbahIndexRoute,
}

const KhutbahRouteWithChildren =
  KhutbahRoute._addFileChildren(KhutbahRouteChildren)

interface QuranRouteChildren {
  QuranIdRoute: typeof QuranIdRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranIdRoute: QuranIdRoute,
  QuranIndexRoute: QuranIndexRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AzkarRoute: AzkarRouteWithChildren,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  HadithRoute: HadithRoute,
  KhutbahRoute: KhutbahRouteWithChildren,
  QuranRoute: QuranRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
