/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as KhutbahRouteImport } from './routes/khutbah'
import { Route as AzkarRouteImport } from './routes/azkar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhutbahIdRouteImport } from './routes/khutbah.$id'

const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const KhutbahRoute = KhutbahRouteImport.update({
  id: '/khutbah',
  path: '/khutbah',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarRoute = AzkarRouteImport.update({
  id: '/azkar',
  path: '/azkar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhutbahIdRoute = KhutbahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KhutbahRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/khutbah': typeof KhutbahRouteWithChildren
  '/quran': typeof QuranRoute
  '/khutbah/$id': typeof KhutbahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/khutbah': typeof KhutbahRouteWithChildren
  '/quran': typeof QuranRoute
  '/khutbah/$id': typeof KhutbahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azkar': typeof AzkarRoute
  '/khutbah': typeof KhutbahRouteWithChildren
  '/quran': typeof QuranRoute
  '/khutbah/$id': typeof KhutbahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/azkar' | '/khutbah' | '/quran' | '/khutbah/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/azkar' | '/khutbah' | '/quran' | '/khutbah/$id'
  id: '__root__' | '/' | '/azkar' | '/khutbah' | '/quran' | '/khutbah/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzkarRoute: typeof AzkarRoute
  KhutbahRoute: typeof KhutbahRouteWithChildren
  QuranRoute: typeof QuranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khutbah': {
      id: '/khutbah'
      path: '/khutbah'
      fullPath: '/khutbah'
      preLoaderRoute: typeof KhutbahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar': {
      id: '/azkar'
      path: '/azkar'
      fullPath: '/azkar'
      preLoaderRoute: typeof AzkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khutbah/$id': {
      id: '/khutbah/$id'
      path: '/$id'
      fullPath: '/khutbah/$id'
      preLoaderRoute: typeof KhutbahIdRouteImport
      parentRoute: typeof KhutbahRoute
    }
  }
}

interface KhutbahRouteChildren {
  KhutbahIdRoute: typeof KhutbahIdRoute
}

const KhutbahRouteChildren: KhutbahRouteChildren = {
  KhutbahIdRoute: KhutbahIdRoute,
}

const KhutbahRouteWithChildren =
  KhutbahRoute._addFileChildren(KhutbahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzkarRoute: AzkarRoute,
  KhutbahRoute: KhutbahRouteWithChildren,
  QuranRoute: QuranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
